# Generated by Django 3.2 on 2021-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=5)),
                ('comment_text', models.TextField()),
                ('can_contact', models.BooleanField()),
                ('contact_info', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='tree_photos')),
            ],
        ),
    ]
