# Generated by Django 3.2 on 2021-09-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treeID', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='approval',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
